// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usdmfoxvhdwuhsaignkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZG1mb3h2aGR3dWhzYWlnbmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzM2MjIsImV4cCI6MjA3MDg0OTYyMn0.Ia0Sf4Wp-tKwO6x5-u0KwRN8xL7HX9j46rAoQhGOZcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});